'use client';
import { useState } from 'react';
import { AppShell, PageHeader, money } from '@/components/ui';
import { usePocketStore } from '@/lib/store';

export default function EventsPage() {
  const store = usePocketStore();
  const [form, setForm] = useState({ name: '', location: '', startDate: '', endDate: '', targetGuests: 20 });
  function submit(e: React.FormEvent) { e.preventDefault(); if (!form.name.trim()) return; store.createEvent({ ...form, location: form.location || 'Remote Location', startDate: form.startDate || '2026-10-01', endDate: form.endDate || '2026-10-05', targetGuests: Number(form.targetGuests) || 20 }); setForm({ name: '', location: '', startDate: '', endDate: '', targetGuests: 20 }); }
  return <AppShell><PageHeader title="Events" description="Create new events and open event detail context for packages, expenses, scenarios, snapshots, and reporting." />
    <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="card p-6"><h2 className="text-xl font-semibold text-ink">Create Event</h2><form onSubmit={submit} className="mt-5 grid gap-3"><input className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Event name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Location" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /><div className="grid grid-cols-2 gap-3"><input type="date" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /><input type="date" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></div><input type="number" className="rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Target guests" value={form.targetGuests} onChange={(e) => setForm({ ...form, targetGuests: Number(e.target.value) })} /><button className="rounded-2xl bg-ink px-4 py-3 text-sm font-semibold text-white">Create Event</button></form></div>
    <div className="card p-6"><h2 className="text-xl font-semibold text-ink">View Events</h2><div className="mt-5 space-y-3">{store.events.map((event) => { const pkgs = store.packages.filter(p => p.eventId === event.id); const exps = store.expenses.filter(x => x.eventId === event.id); const revenue = pkgs.reduce((s,p)=>s+p.price*p.sold,0); const expenseTotal = exps.reduce((s,x)=>s+x.amount,0); return <button key={event.id} onClick={() => store.setSelectedEventId(event.id)} className={`w-full rounded-2xl border p-4 text-left transition ${store.selectedEventId === event.id ? 'border-pocket bg-indigo-50' : 'border-slate-100 bg-white hover:bg-slate-50'}`}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-ink">{event.name}</p><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-pocket">{event.status}</span></div><p className="mt-1 text-sm text-slate-500">{event.location} · {event.startDate} to {event.endDate} · Target {event.targetGuests} guests</p><p className="mt-2 text-xs text-slate-500">Revenue {money(revenue)} · Expenses {money(expenseTotal)}</p></button>})}</div></div></section>
  </AppShell>;
}
