'use client';
import { useState } from 'react';
import { AppShell, EventSelector, PageHeader, StatCard, money, percent } from '@/components/ui';
import { usePocketStore } from '@/lib/store';

export default function ScenariosPage() {
  const store = usePocketStore();
  const [form, setForm] = useState({ name: 'New Scenario', guestLift: 2, priceLift: 5, extraCost: 1000 });
  const averagePrice = store.totals.sold ? store.totals.revenue / store.totals.sold : 0;
  function calc(s: typeof form) { const scenarioRevenue = store.totals.revenue + Number(s.guestLift) * averagePrice * (1 + Number(s.priceLift) / 100); const scenarioExpenses = store.totals.totalExpenses + Number(s.extraCost); const scenarioProfit = scenarioRevenue - scenarioExpenses; const scenarioMargin = scenarioRevenue ? (scenarioProfit / scenarioRevenue) * 100 : 0; return { scenarioRevenue, scenarioExpenses, scenarioProfit, scenarioMargin }; }
  function submit(e: React.FormEvent) { e.preventDefault(); store.addScenario({ name: form.name, guestLift: Number(form.guestLift), priceLift: Number(form.priceLift), extraCost: Number(form.extraCost) }); }
  const preview = calc(form);
  return <AppShell><PageHeader title="Scenario Planning" description="Model conservative, base, and optimistic versions by changing guest count, pricing, and extra cost assumptions." action={<EventSelector {...store} />} />
    <section className="card p-6"><h2 className="text-xl font-semibold text-ink">Build scenario</h2><form onSubmit={submit} className="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-5"><input className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input type="number" className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={form.guestLift} onChange={(e) => setForm({ ...form, guestLift: Number(e.target.value) })} /><input type="number" className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={form.priceLift} onChange={(e) => setForm({ ...form, priceLift: Number(e.target.value) })} /><input type="number" className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={form.extraCost} onChange={(e) => setForm({ ...form, extraCost: Number(e.target.value) })} /><button className="rounded-xl bg-pocket px-3 py-2 text-sm font-semibold text-white">Save Scenario</button></form><div className="mt-5 grid gap-4 md:grid-cols-4"><StatCard label="Scenario Revenue" value={money(preview.scenarioRevenue)} note={form.name} /><StatCard label="Scenario Expenses" value={money(preview.scenarioExpenses)} note="Current + extra cost" /><StatCard label="Scenario Profit" value={money(preview.scenarioProfit)} note="Projected outcome" /><StatCard label="Scenario Margin" value={percent(preview.scenarioMargin)} note="Profitability" /></div></section>
    <section className="mt-6 card p-6"><h2 className="text-xl font-semibold text-ink">Saved scenarios</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{store.eventScenarios.map((s) => { const r = calc(s); return <div key={s.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex justify-between"><p className="font-medium text-ink">{s.name}</p><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-pocket">{percent(r.scenarioMargin)}</span></div><p className="mt-3 text-sm text-slate-500">Guests {s.guestLift >= 0 ? '+' : ''}{s.guestLift} · Price {s.priceLift}% · Extra cost {money(s.extraCost)}</p><p className="mt-2 font-semibold text-ink">Profit {money(r.scenarioProfit)}</p></div>})}</div></section>
  </AppShell>;
}
